// Copies the Material Icons (Round) we use into a TypeScript module so the app
// ships its own icons and never loads anything from a CDN.
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const CATEGORY_ICONS = [
  'shopping_cart', 'restaurant', 'directions_bus', 'directions_car', 'home', 'receipt_long',
  'favorite', 'school', 'shopping_bag', 'movie', 'flight', 'autorenew', 'category',
  'payments', 'handyman', 'card_giftcard', 'trending_up', 'pets', 'fitness_center', 'local_cafe',
  'local_bar', 'phone_iphone', 'wifi', 'bolt', 'checkroom', 'spa', 'child_care', 'sports_esports',
  'music_note', 'menu_book', 'savings', 'account_balance', 'credit_card', 'local_gas_station',
  'train', 'pedal_bike', 'build', 'cleaning_services', 'celebration', 'redeem', 'volunteer_activism',
  'computer', 'headphones', 'local_pharmacy', 'local_hospital', 'bakery_dining', 'local_pizza',
  'icecream', 'sports_soccer', 'park', 'beach_access', 'hotel', 'luggage', 'local_laundry_service',
  'lightbulb', 'local_florist', 'brush', 'camera_alt', 'star', 'paid', 'apartment', 'key',
  'local_parking', 'work', 'cake', 'water_drop', 'smartphone', 'toys', 'casino', 'attach_money',
];

const UI_ICONS = [
  'home', 'insights', 'receipt_long', 'add', 'settings', 'search', 'tune', 'close', 'arrow_back',
  'chevron_left', 'chevron_right', 'check', 'delete', 'edit', 'backspace', 'event', 'repeat', 'image',
  'add_a_photo', 'undo', 'expand_more', 'expand_less', 'download', 'ios_share', 'upload', 'restore',
  'sell', 'info', 'warning', 'cloud_off', 'dark_mode', 'light_mode', 'drag_indicator', 'pause',
  'play_arrow', 'arrow_upward', 'arrow_downward', 'error_outline', 'done', 'language', 'account_balance_wallet',
  'today', 'date_range', 'calendar_month', 'backup', 'refresh', 'system_update', 'add_to_home_screen',
  'keyboard_hide', 'palette', 'more_horiz', 'more_vert', 'filter_list', 'zoom_in', 'north_east', 'south_west',
  'lock', 'verified', 'remove', 'inventory_2', 'wallet', 'pie_chart', 'bar_chart', 'schedule', 'notes',
  'photo_library', 'label', 'currency_exchange', 'first_page', 'view_week', 'brightness_auto',
  'delete_forever', 'check_circle', 'radio_button_unchecked', 'radio_button_checked', 'check_box',
  'check_box_outline_blank', 'shield', 'launch', 'arrow_forward', 'menu', 'swap_vert', 'mood', 'sentiment_satisfied',
  'flag', 'science', 'query_stats', 'event_repeat', 'history', 'save', 'share', 'file_download', 'folder_open',
];

const base = resolve('node_modules/@material-design-icons/svg/round');
const all = [...new Set([...CATEGORY_ICONS, ...UI_ICONS])].sort();
const entries = [];
for (const name of all) {
  let svg;
  try {
    svg = readFileSync(resolve(base, `${name}.svg`), 'utf8');
  } catch {
    console.error(`Missing icon: ${name}`);
    process.exitCode = 1;
    continue;
  }
  const inner = svg.replace(/^<svg[^>]*>/, '').replace(/<\/svg>\s*$/, '').trim();
  entries.push(`  ${JSON.stringify(name)}: ${JSON.stringify(inner)},`);
}

const out = `// Generated by scripts/extract-icons.mjs from @material-design-icons/svg (Apache-2.0). Do not edit.
export const ICON_SVG: Record<string, string> = {
${entries.join('\n')}
};

export const CATEGORY_ICON_KEYS = ${JSON.stringify(CATEGORY_ICONS)} as const;
export type IconKey = keyof typeof ICON_SVG;
`;
writeFileSync(resolve('src/icons/iconPaths.ts'), out);
console.log(`Wrote ${entries.length} icons`);
